### PR TITLE
Feat feature endpoint

### PR DESCRIPTION
**Pull request by marcenko**
- New Endpoint to get a feature by id without additional information.
- Added an optional param to filter feature response by type

### CODE REVIEW

**Review by xgui3783 — COMMENTED** [review]
Thanks for working on this.

I think we should add `model_type`, just like we added `model_id` so we could:

- efficiently filter features without calling `to_model` method (which can be expensive)
- potentially have a way to enumerate feature names/types

**Comment by xgui3783** [comment]
related: https://github.com/FZJ-INM1-BDA/siibra-python/pull/170 adding `.get_model_type()` class method to all features (well, all `JSONSerializable` derived classes. )

once aforementioned PR is merged, we could more efficiently and correctly filter feature by type.

**Comment by xgui3783** [comment]
Is this the filter by type PR you were talking about @marcenko ? It looks ready to me, I think?

**Comment by marcenko** [comment]
Yes, thats the one.
The filter for region features is not working 100%, but that must be tackled on siibra-python side.

**Comment by xgui3783** [comment]
> Yes, thats the one. The filter for region features is not working 100%, but that must be tackled on siibra-python side.

can you give me an example when it doesn't work? ping @marcenko

**Pull request merged**
